version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:1.8.3
     working_directory: /go/src/github.com/r3labs/authenticator
     steps:
       - checkout
       - run: go test -v -cover ./...
